title = "Gitleaks Configuration for Password Analyzer"

[[rules]]
id = "no-password-examples"
description = "Ignore password examples in comments"
regex = '''password.*['"].*['"]'''
tags = ["skip", "false-positive"]