name: SSDLC CI/CD Pipeline for Password Analyzer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  security-analysis:
    name: Security Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Scan for secrets with Gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          scan-dir: '.'

      - name: Run ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.10.0
        with:
          target: 'https://mmmykoladiploma.github.io/Password-Analyzer/'
          rules_file_name: 'password-analyzer-rules.tsv'
          cmd_options: '-a -j -l PASS'
          artifact_name: zap-scan-report

  quality-analysis:
    name: Code Quality Analysis
    runs-on: ubuntu-latest
    needs: security-analysis
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: HTML Validation
        uses: Cyb3r-Jak3/html5validator-action@v0.4.1

      - name: ESLint (if JavaScript files exist)
        uses: stefanoeb/eslint-action@v1
        continue-on-error: true

      - name: Run Lighthouse CI
        uses: treosh/lighthouse-ci-action@v9
        with:
          urls: |
            https://mmmykoladiploma.github.io/Password-Analyzer/
          uploadArtifacts: true
          temporaryPublicStorage: true

  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: [security-analysis, quality-analysis]
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2